### ISSUE TITLE
[建议] 左侧歌曲序号显示其真实序号

### ISSUE THREAD

**Issue by Lukoning** [thy646742/ArtistAllSongs#5]
如图，当前在19页，按理说该页最后一首歌曲的序号是20x19=380，但实际显示的序号仍然为20

![屏幕截图 2024-07-30 231752](https://github.com/user-attachments/assets/2027358f-afec-40c8-8161-c799985fdc01)

**Comment by thy646742** [comment]
套了一个`<ul>`标签，带上一个叫`tlistorder`的计数器的`counter-reset`，可以被网易云自带的样式识别。但是我觉得改的比较潦草代码上不是很好看，因为有两个`<ul>`了很奇怪。要是能在不影响识别的情况下把这个表的结构改的舒服点，欢迎pull request，十分感谢orz
